version: '3'
services:
  db:
    image: postgres
    volumes:
      - mydocs_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nghiant11
      POSTGRES_PASSWORD: magical_password
      POSTGRES_DB: mydocs
volumes:
  mydocs_data: {}